var books = [
    {
      "title":"Maskerade",
      "author":"Terry Pratchett",
      "picture":"../imgs/maskerade_discworld.jpg",
      "description":"THE SHOW MUST GO ON, AS MURDER, MUSIC AND MAYHEM RUN RIOT IN THE NIGHT... The Opera House, Ankh-Morpork...A huge, rambling building, where innocent young sopranos are lured to their destiny by a strangely familiar evil mastermind in a hideously deformed evening dress...At least, he hopes so. But Granny Weatherwax, Discworld's most famous witch, is in the audience. And she doesn't hold with that sort of thing. So there's going to be trouble (but nevertheless a good evening's entertainment with murders you can really hum...)",
      "date_added":"20160113",
      "genre1":"Fantasy",
      "genre2":"Comedy",
      "available":false,
    },
    {
      "title":"Mort",
      "author":"Terry Pratchett",
      "picture":"../imgs/mort_discworld.jpg",
      "description":"It is known as the Discworld. It is a flat planet, supported on the backs of four elephants, who in turn stand on the back of the great turtle A'Tuin as it swims majestically through space. And it is quite possibly the funniest place in all of creation...Death comes to us all. When he came to Mort, he offered him a job. After being assured that being dead was not compulsory, Mort accepted. However, he soon found that romantic longings did not mix easily with the responsibilities of being Death's apprentice. Terry Pratchett's hilarious fourth Discworld novel established once and for all that Death really is a laughing matter...",
      "date_added":"20160516",
      "genre1":"Fantasy",
      "genre2":"Comedy",
      "available":true,
    },
    {
      "title":"Hogfather",
      "author":"Terry Pratchett",
      "picture":"../imgs/hogfather.jpg",
      "description":"IT'S THE NIGHT BEFORE HOGSWATCH AND IT'S TOO QUIET. Where is the big jolly fat man? Why is Death creeping down chimneys and trying to say Ho Ho Ho? The darkest night of the year is getting a lot darker...Susan the gothic governess has got to sort it out by morning, otherwise there won't be a morning. Ever again...The 20th Discworld novel is a festive feast of darkness and Death (but with jolly robins and tinsel too). As they say: You'd better watch out...",
      "date_added":"20160330",
      "genre1":"Fantasy",
      "genre2":"Comedy",
      "available":false,
    },
    {
      "title":"Reaper Man",
      "author":"Terry Pratchett",
      "picture":"../imgs/reaper_man_discworld.jpg",
      "description":"DEATH IS MISSING - PRESUMED...ER...GONE. Which leads to the kind of chaos you always get when an important public service is withdrawn. Meanwhile, on a little farm far, far away, a tall, dark stranger is turning out to be really good with a scythe. There's a harvest to be gathered in...",
      "date_added":"NA",
      "genre1":"Fantasy",
      "genre2":"Comedy",
      "available":true,
    },
    {
      "title":"Guards! Guards!",
      "author":"Terry Pratchett",
      "picture":"../imgs/guards_guards_discworld.jpg",
      "description":"This is where the dragons went. They lie...not dead, not asleep, but...dormant. And although the space they occupy isn't like normal space, nevertheless they are packed in tightly. They could put you in mind of a can of sardines, if you thought sardines were huge and scaly. And presumably, somewhere, there's a key...GUARDS! GUARDS! is the 8th Discworld novel - and after this, dragons will never be the same again!",
      "date_added":"NA",
      "genre1":"Fantasy",
      "genre2":"Comedy",
      "available":true,
    },
    {
      "title":"Fellowship of the Ring",
      "author":"JRR Tolkien",
      "picture":"../imgs/fellowship_ring.jpg",
      "description":"Sauron, the Dark Lord, has gathered to him all the Rings of Power - the means by which he intends to rule Middle-earth. All he lacks in his plans for dominion is the One Ring - the ring that rules them all - which has fallen into the hands of the hobbit, Bilbo Baggins. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose. ",
      "date_added":"20151201",
      "genre1":"Fantasy",
      "genre2":"-",
      "available":true,
    },
    {
      "title":"Two Towers",
      "author":"JRR Tolkien",
      "picture":"../imgs/two_towers.jpg",
      "description":"Frodo and the Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in the battle with an evil spirit in the Mines of Moria; and at the Falls of Rauros, Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape the rest of the company were attacked by Orcs. Now they continue their journey alone down the great River Anduin - alone, that is, save for the mysterious creeping figure that follows wherever they go.",
      "date_added":"20151202",
      "genre1":"Fantasy",
      "genre2":"-",
      "available":true,
    },
    {
      "title":"Return of the King",
      "author":"JRR Tolkien",
      "picture":"../imgs/return_king.jpg",
      "description":"The armies of the Dark Lord Sauron are massing as his evil shadow spreads even wider. Men, Dwarves, Elves and Ents unite forces to do battle against the Dark. Meanwhile, Frodo and Sam struggle further into Mordor, guided by the treacherous creature Gollum, in their heroic quest to destroy the One Ring...",
      "date_added":"20151203",
      "genre1":"Fantasy",
      "genre2":"-",
      "available":true,
    },
    {
      "title":"Harry Potter and the Philosophers Stone",
      "author":"JK Rowling",
      "picture":"../imgs/hp_philosohers_stone.jpg",
      "description":"Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin! ",
      "date_added":"20151120",
      "genre1":"Fantasy",
      "genre2":"-",
      "available":true,
    },
    {
      "title":"Harry Potter and the Chamber of Secrets",
      "author":"JK Rowling",
      "picture":"../imgs/hp_chamber_secrets.jpg",
      "description":"Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as though turned to stone ...Dobby's sinister predictions seem to be coming true.",
      "date_added":"20151122",
      "genre1":"Fantasy",
      "genre2":"-",
      "available":true,
    },
    {
      "title":"Harry Potter and the Prisoner of Azkaban",
      "author":"JK Rowling",
      "picture":"../imgs/hp_prisoner_azkaban.jpg",
      "description":"When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far from ordinary year at Hogwarts for Harry Potter. Sirius Black, escaped mass-murderer and follower of Lord Voldemort, is on the run - and they say he is coming after Harry. In his first ever Divination class, Professor Trelawney sees an omen of death in Harry's tea leaves ...But perhaps most terrifying of all are the Dementors patrolling the school grounds, with their soul-sucking kiss. ",
      "date_added":"20151124",
      "genre1":"Fantasy",
      "genre2":"-",
      "available":true,
    },
    {
      "title":"1984",
      "author":"George Orwell",
      "picture":"../imgs/1984.jpg",
      "description":" April, 1984. 13:00. Comrade 6079, Winston Smith, thinks a thought, starts a diary, and falls in love. But Big Brother is watching him - and the door to Room 101 can swing open in the blink of an eye. This major new production explores the world inside Winston Smith's head, as well as the world without, and catches the euphoria and bliss buried deep underneath the cold face of Big Brother.",
      "date_added":"20151124",
      "genre1":"Sci-fi",
      "genre2":"-",
      "available":true,
    },
    {
      "title":"Brave New World",
      "author":"Aldous Huxley",
      "picture":"../imgs/brave_new_world.jpg",
      "description":"Far in the future, the World Controllers have created the ideal society. Through clever use of genetic engineering, brainwashing and recreational sex and drugs all its members are happy consumers. Bernard Marx seems alone harbouring an ill-defined longing to break free. A visit to one of the few remaining Savage Reservations where the old, imperfect life still continues, may be the cure for his distress...",
      "date_added":"20151124",
      "genre1":"Sci-fi",
      "genre2":"-",
      "available":true,
    },
];
