var books = [
    {
      "title":"Maskerade",
      "author":"Terry Pratchett",
      "picture":"../imgs/maskerade_discworld.jpg",
      "description":"../book_desc/maskerade_discworld.txt",
      "date_added":"20160113",
      "genre1":"Fantasy",
      "genre2":"Comedy",
      "available":false,
    },
    {
      "title":"Mort",
      "author":"Terry Pratchett",
      "picture":"../imgs/mort_discworld.jpg",
      "description":"../book_desc/mort.txt",
      "date_added":"20160516",
      "genre1":"Fantasy",
      "genre2":"Comedy",
      "available":true,
    },
    {
      "title":"Hogfather",
      "author":"Terry Pratchett",
      "picture":"../imgs/hogfather.jpg",
      "description":"../book_desc/hogfather.txt",
      "date_added":"20160330",
      "genre1":"Fantasy",
      "genre2":"Comedy",
      "available":false,
    },
    {
      "title":"Reaper Man",
      "author":"Terry Pratchett",
      "picture":"../imgs/reaper_man_discworld.jpg",
      "description":"../book_desc/reaper_man.txt",
      "date_added":"NA",
      "genre1":"Fantasy",
      "genre2":"Comedy",
      "available":true,
    },
    {
      "title":"Guards! Guards!",
      "author":"Terry Pratchett",
      "picture":"../imgs/guards_guards_discworld.jpg",
      "description":"../book_desc/guards_guards.txt",
      "date_added":"NA",
      "genre1":"Fantasy",
      "genre2":"Comedy",
      "available":true,
    },
    {
      "title":"Fellowship of the Ring",
      "author":"JRR Tolkien",
      "picture":"../imgs/fellowship_ring.jpg",
      "description":"../book_desc/fellowship_ring.txt",
      "date_added":"20151201",
      "genre1":"Fantasy",
      "genre2":"-",
      "available":true,
    },
    {
      "title":"Two Towers",
      "author":"JRR Tolkien",
      "picture":"../imgs/two_towers.jpg",
      "description":"../book_desc/two_towers.txt",
      "date_added":"20151202",
      "genre1":"Fantasy",
      "genre2":"-",
      "available":true,
    },
    {
      "title":"Return of the King",
      "author":"JRR Tolkien",
      "picture":"../imgs/return_king.jpg",
      "description":"../book_desc/return_king.txt",
      "date_added":"20151203",
      "genre1":"Fantasy",
      "genre2":"-",
      "available":true,
    },
    {
      "title":"Harry Potter and the Philosophers Stone",
      "author":"JK Rowling",
      "picture":"../imgs/hp_philosophers_stone.jpg",
      "description":"../book_desc/hp_philosophers_stone.txt",
      "date_added":"20151120",
      "genre1":"Fantasy",
      "genre2":"-",
      "available":true,
    },
    {
      "title":"Harry Potter and the Chamber of Secrets",
      "author":"JK Rowling",
      "picture":"../imgs/hp_chamber_secrets.jpg",
      "description":"../book_desc/hp_chamber_secrets.txt",
      "date_added":"20151122",
      "genre1":"Fantasy",
      "genre2":"-",
      "available":true,
    },
    {
      "title":"Harry Potter and the Prisoner of Azkaban",
      "author":"JK Rowling",
      "picture":"../imgs/hp_prisoner_azkaban.jpg",
      "description":"../book_desc/hp_prisoner_azkaban.txt",
      "date_added":"20151124",
      "genre1":"Fantasy",
      "genre2":"-",
      "available":true,
    },
];
